name: Update VRChat Members

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Update VRChat counter
        env:
          VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}
        run: node update-vrchat.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add vrchat.xml
          git commit -m "Update VRChat members" || exit 0
          git push